name: Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: gulp clean build-bundle
      
    - name: Publish to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        # token: ${{ secrets.GITHUB_TOKEN }}
        # ssh-key: ${{ secrets.DEPLOY_KEY }}
        branch: master
        folder: dist
        target-folder: ~/dist
